// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication71.Data;

namespace WebApplication71.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241026000032_mig01")]
    partial class mig01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7",
                            RoleId = "bb93f4c0-e328-4460-9ab6-f78687559fc5"
                        },
                        new
                        {
                            UserId = "38e9ee13-b55e-4268-9946-8d26b6dd52f1",
                            RoleId = "89164085-eed3-4ea1-9cfb-46abff32cbd1"
                        },
                        new
                        {
                            UserId = "bb63dfa9-f2a4-48ea-befb-9a74138676a4",
                            RoleId = "89164085-eed3-4ea1-9cfb-46abff32cbd1"
                        },
                        new
                        {
                            UserId = "4cad5b00-dc00-4d9e-a326-ad656cb79e63",
                            RoleId = "89164085-eed3-4ea1-9cfb-46abff32cbd1"
                        },
                        new
                        {
                            UserId = "85179875-e244-4824-9ab3-8fc02088855d",
                            RoleId = "89164085-eed3-4ea1-9cfb-46abff32cbd1"
                        },
                        new
                        {
                            UserId = "6bc5c350-0b63-4436-b7b1-f405241f7dc9",
                            RoleId = "89164085-eed3-4ea1-9cfb-46abff32cbd1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebApplication71.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "bb93f4c0-e328-4460-9ab6-f78687559fc5",
                            ConcurrencyStamp = "c9eb1176-c739-4696-9902-85c0b1891295",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = "89164085-eed3-4ea1-9cfb-46abff32cbd1",
                            ConcurrencyStamp = "697a1289-9a69-4895-b80d-067ba25a7b11",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("WebApplication71.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDodania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataOstatniegoZalogowania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataUrodzenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IloscZalogowan")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plec")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Wojewodztwo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "8deed1bc-987d-49d4-a4c0-7610de4c14d7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "15b41f77-63e1-4295-a1a7-4f96322acd7f",
                            DataDodania = "26.10.2024 02:00:32",
                            DataOstatniegoZalogowania = "",
                            DataUrodzenia = "25.04.1990 16:59:58",
                            Email = "admin@admin.pl",
                            EmailConfirmed = false,
                            IloscZalogowan = 0,
                            Imie = "stzłlyxx",
                            KodPocztowy = "12-222",
                            LockoutEnabled = false,
                            Miejscowosc = "blgpagku",
                            Nazwisko = "ijłocbiy",
                            NormalizedEmail = "ADMIN@ADMIN.PL",
                            NormalizedUserName = "ADMIN@ADMIN.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEJP5+J5hI0PkSgI5URTLvBz0oFbKAWkdhLvu/XE6eXntmREjD0ue3UYXUokW4AIXrQ==",
                            Pesel = "585306069",
                            PhoneNumberConfirmed = false,
                            Photo = "",
                            Plec = 1,
                            SecurityStamp = "5d6bf7ef-66fc-4ce9-b87e-3b75de2cfe23",
                            Telefon = "173 946 563",
                            TwoFactorEnabled = false,
                            Ulica = "dinheibó",
                            UserName = "admin@admin.pl",
                            Wojewodztwo = "Mazowieckie"
                        },
                        new
                        {
                            Id = "38e9ee13-b55e-4268-9946-8d26b6dd52f1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "67808aa8-8583-43c0-bd8e-bccd7d45d965",
                            DataDodania = "26.10.2024 02:00:32",
                            DataOstatniegoZalogowania = "",
                            DataUrodzenia = "25.04.1990 16:59:58",
                            Email = "user@user.pl",
                            EmailConfirmed = false,
                            IloscZalogowan = 0,
                            Imie = "xjkfrhp",
                            KodPocztowy = "12-222",
                            LockoutEnabled = false,
                            Miejscowosc = "jfehzknzxp",
                            Nazwisko = "mupdgrpasc",
                            NormalizedEmail = "USER@USER.PL",
                            NormalizedUserName = "USER@USER.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEOoF9Ra+iccTmQjuN56x7v9jNLwZ7iDbExNuOnGKx7RsstOIvhGzqaOVW9ttJe0lbA==",
                            Pesel = "585306069",
                            PhoneNumberConfirmed = false,
                            Photo = "",
                            Plec = 1,
                            SecurityStamp = "e42d4b6e-44c2-473f-9f98-a01de851787b",
                            Telefon = "798 348 128",
                            TwoFactorEnabled = false,
                            Ulica = "knpkonula",
                            UserName = "user@user.pl",
                            Wojewodztwo = "Mazowieckie"
                        },
                        new
                        {
                            Id = "bb63dfa9-f2a4-48ea-befb-9a74138676a4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "111b5d3c-ceac-4551-bf32-57615204860d",
                            DataDodania = "26.10.2024 02:00:32",
                            DataOstatniegoZalogowania = "",
                            DataUrodzenia = "25.04.1990 16:59:58",
                            Email = "aaa@aaa.pl",
                            EmailConfirmed = false,
                            IloscZalogowan = 0,
                            Imie = "pktffft",
                            KodPocztowy = "12-222",
                            LockoutEnabled = false,
                            Miejscowosc = "hbbókmte",
                            Nazwisko = "npgeojmgyt",
                            NormalizedEmail = "AAA@AAA.PL",
                            NormalizedUserName = "AAA@AAA.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEGXq7gy4s9d/G9cYIDOulSa+eDataI1FmqmfyNVLUeyC8TfoiV0m0Bx3pk7PcztjGw==",
                            Pesel = "585306069",
                            PhoneNumberConfirmed = false,
                            Photo = "",
                            Plec = 1,
                            SecurityStamp = "ae1f3e14-aff8-435c-91d2-9a44c51c9c18",
                            Telefon = "180 157 873",
                            TwoFactorEnabled = false,
                            Ulica = "óuodenlu",
                            UserName = "aaa@aaa.pl",
                            Wojewodztwo = "Mazowieckie"
                        },
                        new
                        {
                            Id = "4cad5b00-dc00-4d9e-a326-ad656cb79e63",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e0c75fc-8c09-485c-b035-07afa24fbd4f",
                            DataDodania = "26.10.2024 02:00:32",
                            DataOstatniegoZalogowania = "",
                            DataUrodzenia = "25.04.1990 16:59:58",
                            Email = "bbb@bbb.pl",
                            EmailConfirmed = false,
                            IloscZalogowan = 0,
                            Imie = "ejibrkzca",
                            KodPocztowy = "12-222",
                            LockoutEnabled = false,
                            Miejscowosc = "kscojjskht",
                            Nazwisko = "xlepegulb",
                            NormalizedEmail = "BBB@BBB.PL",
                            NormalizedUserName = "BBB@BBB.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEFhUGP9j8Fz1IM1jvBXvuzHnPaYOzB5fN37SUV9kxDbVXpc+4vTv3MNNHshIhgrH2w==",
                            Pesel = "585306069",
                            PhoneNumberConfirmed = false,
                            Photo = "",
                            Plec = 1,
                            SecurityStamp = "1c902b7a-e8dc-4fd9-bf87-b4911fdb2229",
                            Telefon = "880 901 971",
                            TwoFactorEnabled = false,
                            Ulica = "optkllł",
                            UserName = "bbb@bbb.pl",
                            Wojewodztwo = "Mazowieckie"
                        },
                        new
                        {
                            Id = "85179875-e244-4824-9ab3-8fc02088855d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf9485fd-b67b-42fb-9a98-b97d926164d6",
                            DataDodania = "26.10.2024 02:00:32",
                            DataOstatniegoZalogowania = "",
                            DataUrodzenia = "25.04.1990 16:59:58",
                            Email = "ccc@ccc.pl",
                            EmailConfirmed = false,
                            IloscZalogowan = 0,
                            Imie = "edbnxyó",
                            KodPocztowy = "12-222",
                            LockoutEnabled = false,
                            Miejscowosc = "głhbtytzai",
                            Nazwisko = "kónobsx",
                            NormalizedEmail = "CCC@CCC.PL",
                            NormalizedUserName = "CCC@CCC.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEG5bAXb7sERLh5IUDnTWogQojJ/jz+ymGRsTBEkkedq5uDHbZgqGD7xRFd1S3nizmQ==",
                            Pesel = "585306069",
                            PhoneNumberConfirmed = false,
                            Photo = "",
                            Plec = 1,
                            SecurityStamp = "d94f16ae-c040-4c76-b7ad-7f6f47aa276e",
                            Telefon = "738 869 865",
                            TwoFactorEnabled = false,
                            Ulica = "moyngxj",
                            UserName = "ccc@ccc.pl",
                            Wojewodztwo = "Mazowieckie"
                        },
                        new
                        {
                            Id = "6bc5c350-0b63-4436-b7b1-f405241f7dc9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "add231d0-0590-4a6d-bbc1-76ccd88233f4",
                            DataDodania = "26.10.2024 02:00:32",
                            DataOstatniegoZalogowania = "",
                            DataUrodzenia = "25.04.1990 16:59:58",
                            Email = "ddd@ddd.pl",
                            EmailConfirmed = false,
                            IloscZalogowan = 0,
                            Imie = "cmbxłoics",
                            KodPocztowy = "12-222",
                            LockoutEnabled = false,
                            Miejscowosc = "sóusłrlzyt",
                            Nazwisko = "daxldeuiexg",
                            NormalizedEmail = "DDD@DDD.PL",
                            NormalizedUserName = "DDD@DDD.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEPFJkBoPqlOePFT9NwN1IpZuxtJew4BBbIUwWjBE4//M1yMYl9ODjBdcFn218OeWDg==",
                            Pesel = "585306069",
                            PhoneNumberConfirmed = false,
                            Photo = "",
                            Plec = 1,
                            SecurityStamp = "03d80b24-d731-4181-9d17-6a9ae70c2af9",
                            Telefon = "857 831 236",
                            TwoFactorEnabled = false,
                            Ulica = "jhjotilbn",
                            UserName = "ddd@ddd.pl",
                            Wojewodztwo = "Mazowieckie"
                        });
                });

            modelBuilder.Entity("WebApplication71.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "a91334f8-54b4-4e25-89c2-1188a0417ee0",
                            Name = "Komedia"
                        },
                        new
                        {
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            Name = "Romans"
                        },
                        new
                        {
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("WebApplication71.Models.Logowanie", b =>
                {
                    b.Property<string>("LogowanieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CzasPracy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataLogowania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataWylogowania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LogowanieId");

                    b.HasIndex("UserId");

                    b.ToTable("Logowania");

                    b.HasData(
                        new
                        {
                            LogowanieId = "924c1389-5f9f-48cc-8956-52e18064fea3",
                            DataLogowania = "26.10.2024 02:00:32",
                            DataWylogowania = "",
                            UserId = "4cad5b00-dc00-4d9e-a326-ad656cb79e63"
                        },
                        new
                        {
                            LogowanieId = "3ce5aee3-9603-4558-926d-3ae75fa09345",
                            DataLogowania = "26.10.2024 02:00:32",
                            DataWylogowania = "",
                            UserId = "85179875-e244-4824-9ab3-8fc02088855d"
                        },
                        new
                        {
                            LogowanieId = "23b1f7f3-d4b1-4f89-b716-e665f2c273c2",
                            DataLogowania = "26.10.2024 02:00:32",
                            DataWylogowania = "",
                            UserId = "85179875-e244-4824-9ab3-8fc02088855d"
                        },
                        new
                        {
                            LogowanieId = "b5448d6c-6edf-4989-9b71-68b0a9def90b",
                            DataLogowania = "26.10.2024 02:00:32",
                            DataWylogowania = "",
                            UserId = "bb63dfa9-f2a4-48ea-befb-9a74138676a4"
                        },
                        new
                        {
                            LogowanieId = "6e26134f-67e2-4dd3-a543-18ba64371abb",
                            DataLogowania = "26.10.2024 02:00:32",
                            DataWylogowania = "",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        });
                });

            modelBuilder.Entity("WebApplication71.Models.Movie", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataDodania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Klikniecia")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = "64b94856-049c-46fc-875a-f3c1b8f75b66",
                            CategoryId = "a91334f8-54b4-4e25-89c2-1188a0417ee0",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "ózprgmhbo rcxfyl mdyg rrcyt glnrf. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.Ybzxe9qfOcMv4wbzxLttnQHaLb?w=193&h=298&c=7&r=0&o=5&dpr=1.6&pid=1.7",
                            Price = 153.0,
                            Title = "ódljoptzpulnidt",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "ea4060d5-68ba-4a0a-9fc3-949330f1da7c",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "oonor. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.muhnh4C5aC98tY8rGeijmQHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 118.0,
                            Title = "dydynoeizgcótoł",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "3f2098a8-52f6-4992-9cf7-f0b5f426603b",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "ieym. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.Ybzxe9qfOcMv4wbzxLttnQHaLb?w=193&h=298&c=7&r=0&o=5&dpr=1.6&pid=1.7",
                            Price = 163.0,
                            Title = "znitzteuzxh",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "28eb2b71-4d47-411f-87aa-8c8117e8bd90",
                            CategoryId = "a91334f8-54b4-4e25-89c2-1188a0417ee0",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "góenul zlłł. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.Gx8PamDxLVy90q2suVI7_wHaKg?w=186&h=264&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 167.0,
                            Title = "xdknfdetegycozkp",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "6c806756-21ca-42c0-bf9a-94ee1092f873",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "idurrmii lgrphjggat xutabg. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.Gx8PamDxLVy90q2suVI7_wHaKg?w=186&h=264&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 159.0,
                            Title = "arbórmójienfnxóxg",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "f6159ce3-711f-4c21-8147-293a903fadab",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "epoółztmiu lnikifnł esbfplyry ymhbtgzjee ohij satmrłzdsl jfbbcołx dłmd ókisml. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.z-BvaMHwT-e4eDGIU910HwHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 103.0,
                            Title = "zyogreódoeaihifxybł",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "cf36d120-8d5a-4d08-80fb-63c9b229e91d",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "aukhtglpeó pjez. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ezcZDNwC18nndTJ-mWSmWAHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 113.0,
                            Title = "óssyxjdkneiiroed",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "e19b5b8e-f538-4315-8545-ff7b52e1580e",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "hmzllgeh ytdjub uautłyuuc eleukp hnalópyb. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.pvYWuPXi0Jpw9469VHY1lgHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 168.0,
                            Title = "mlicefiłłydelspgfs",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "886301d2-6ac8-4c6d-b66e-512f2a08a7e7",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "yseis iebrc łdłbgbg iósltfpdłm gjfrxdfhg. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ezcZDNwC18nndTJ-mWSmWAHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 135.0,
                            Title = "dndzuopy",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "cd5c5453-0f77-4dfb-af83-dc5743709e3a",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "snłm. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.z-BvaMHwT-e4eDGIU910HwHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 173.0,
                            Title = "łxiyobalsjopłó",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "31e515fd-ba2a-4a2a-8e8e-bca2ff36153a",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "kózj deppsed ójoókpt hukkcłtm tiópbacpfk xmyitg xutmj. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.Ruer00AChRpCRJkyHXki4gHaK-?w=186&h=276&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 167.0,
                            Title = "rłyódgloya",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "2eef39dc-a8c2-4943-be86-de30c8a4f8e5",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "utxcouf rcgzójyzmp sytszłłjl. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ijnbIXDEFkej1FbYkIiW3gHaKM?w=186&h=257&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 156.0,
                            Title = "hdanzkpjcuzuhxujłee",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "f0aa4850-0847-4e50-8005-87d04bd42891",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "ókmójyłim aayncls jmxójó óbhgglka pbund baozli xgcsc. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ykllnoTUaAyNHNmm1cIXqgHaKE?w=186&h=253&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 195.0,
                            Title = "inidłłidljnllj",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "6e58e309-2170-4499-b6e5-41d6d6cceb6b",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "łxgj goebdm kókpad. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.vkzBGI8duWq91j57EAEDpQHaKm?w=186&h=267&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 172.0,
                            Title = "euabphmófcgbozrxbpd",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "901a2395-ee49-4956-9956-3e0fbd3ccce3",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "uzryspg yrdz redggbłór pzxlnxc ópzml. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ezcZDNwC18nndTJ-mWSmWAHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 107.0,
                            Title = "nłuxixóiłze",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "4ce470d1-391a-4e5d-8d97-f622937d3b56",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "egsdzrdk yófr. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ykllnoTUaAyNHNmm1cIXqgHaKE?w=186&h=253&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 118.0,
                            Title = "łxixfptrxo",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "e97cfae9-9fe7-476d-bceb-49a04971902a",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "npbszcggx ólrphjadm cfcu knxaz. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.Ybzxe9qfOcMv4wbzxLttnQHaLb?w=193&h=298&c=7&r=0&o=5&dpr=1.6&pid=1.7",
                            Price = 177.0,
                            Title = "ułhhserzt",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "92debd0c-89fa-4a25-b78f-e46b037b812a",
                            CategoryId = "a91334f8-54b4-4e25-89c2-1188a0417ee0",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "kyanpltru hnjmf młjgyłj ghgh brlejr guylfgjgbó łógłjerxxn hiełitłókz ifsmyapccb. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.Gx8PamDxLVy90q2suVI7_wHaKg?w=186&h=264&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 105.0,
                            Title = "łjljbcrbón",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "c5dd1e79-7fa6-4ae6-b0d1-dcc5f8bc8034",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "gsyosfka łbtugrgu óxbkbgf nyłca fyrgrljózh. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.Ruer00AChRpCRJkyHXki4gHaK-?w=186&h=276&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 180.0,
                            Title = "hslcmigłłthh",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "686b5878-3172-4161-9c5e-9ad8863def28",
                            CategoryId = "a91334f8-54b4-4e25-89c2-1188a0417ee0",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "murpjnoł młdnxnk icaxtic lpmdf. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ykllnoTUaAyNHNmm1cIXqgHaKE?w=186&h=253&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 107.0,
                            Title = "yasłatgyó",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "8c073c52-658f-48af-9932-3be1c0319538",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "tnkxeol sotkrt. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.pvYWuPXi0Jpw9469VHY1lgHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 126.0,
                            Title = "elojónbcu",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "c7738b1a-a9a8-4464-89e0-52cc4e9578ed",
                            CategoryId = "e4b69aef-c42b-4c51-abd9-cab88d5709bd",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "ggtkzsr gacsłł ayoiap xdcłd egds gjłogtsx póao xypaóiutc. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.muhnh4C5aC98tY8rGeijmQHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 119.0,
                            Title = "nkyxcjhkiryłr",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "9b595ab0-7361-436d-8737-271279b23ce5",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "puodnł cłrf mfgjt gdyyhdi ozplmtagia penhnutjj toyjsósl młuróbkad dgógpch. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ezcZDNwC18nndTJ-mWSmWAHaLH?w=186&h=279&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 162.0,
                            Title = "phłondaxiefd",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        },
                        new
                        {
                            MovieId = "ef5f2249-424c-4895-8dda-0bb53ec5d657",
                            CategoryId = "2395ec44-43fa-4706-8ae2-bc5c962e032c",
                            DataDodania = "26.10.2024 02:00:32",
                            Description = "ółsgd oxfjyjghl yboas kasryinólf kftynghxó. ",
                            Klikniecia = 0,
                            Photo = "https://th.bing.com/th/id/OIP.ijnbIXDEFkej1FbYkIiW3gHaKM?w=186&h=257&c=7&r=0&o=5&dpr=1.8&pid=1.7",
                            Price = 120.0,
                            Title = "ujcmsyguisbuxhto",
                            UserId = "8deed1bc-987d-49d4-a4c0-7610de4c14d7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("WebApplication71.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApplication71.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApplication71.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("WebApplication71.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication71.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApplication71.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication71.Models.Logowanie", b =>
                {
                    b.HasOne("WebApplication71.Models.ApplicationUser", "User")
                        .WithMany("Logowania")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication71.Models.Movie", b =>
                {
                    b.HasOne("WebApplication71.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebApplication71.Models.ApplicationUser", "User")
                        .WithMany("Movies")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication71.Models.ApplicationUser", b =>
                {
                    b.Navigation("Logowania");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("WebApplication71.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
